<?php
/**
 * HelloBotz – Centralized pricing configuration (source of truth)
 * All plan prices in INR. USD derived via INR_TO_USD_RATE.
 */
return [
  'currency_default' => 'INR',
  'INR_TO_USD_RATE' => 0.012, // configurable – not a live FX feed
  'gst_rate' => 0.18,
  'trial_days' => 14,
  'register_url' => 'https://hellobotz.com/auth/register',
  'whatsapp' => '919638911838',

  'plans' => [
    'growth' => [
      'id' => 'growth',
      'name' => 'Growth',
      'badge' => null,
      'tagline' => 'For businesses starting out on WhatsApp',
      'channels' => ['WhatsApp'],
      'monthly' => 1999,
      'yearly' => 19990,
      'setup_fee_monthly' => 2999,
      'setup_fee_yearly' => 0,
      'cta' => 'Start Free',
      'features' => [
        '50,000 contacts & conversations',
        '500 campaigns / month',
        '100 AI prompts',
        '3 team seats',
        'Priority support',
        '25 bot flows',
        '30 tags',
        'WhatsApp channel',
      ],
    ],
    'pro' => [
      'id' => 'pro',
      'name' => 'Pro',
      'badge' => 'MOST POPULAR',
      'tagline' => 'Full power across every channel',
      'channels' => ['WhatsApp', 'Instagram', 'Facebook', 'Telegram'],
      'monthly' => 4999,
      'yearly' => 49990,
      'setup_fee_monthly' => 0,
      'setup_fee_yearly' => 0,
      'cta' => 'Start Free',
      'features' => [
        '100,000 contacts & conversations',
        '2,000 campaigns / month',
        '500 AI prompts',
        '10 team seats',
        'Dedicated support',
        '20 AI calling agent credits',
        '50 bot flows',
        '60 custom fields',
        '60 tags',
        '60 WhatsApp forms',
        '20 appointment bookings',
        '15 Kanban funnels',
        '10 workspaces',
        '500 MB file limit',
        'WhatsApp, Instagram, Facebook, Telegram',
      ],
    ],
    'business' => [
      'id' => 'business',
      'name' => 'Business',
      'badge' => 'BEST VALUE',
      'tagline' => 'Unlimited scale for serious operations',
      'channels' => ['WhatsApp', 'Instagram', 'Facebook', 'Telegram'],
      'monthly' => 7999,
      'yearly' => 76790,
      'setup_fee_monthly' => 0,
      'setup_fee_yearly' => 0,
      'cta' => 'Start Free',
      'features' => [
        'Unlimited contacts & conversations',
        '10,000 campaigns / month',
        '2,000 AI prompts',
        '25 team seats',
        'Dedicated account manager',
        '50 AI calling agent credits',
        '150 bot flows',
        '100 custom fields',
        '100 tags',
        '100 WhatsApp forms',
        '50 appointment bookings',
        '30 Kanban funnels',
        '25 workspaces',
        '1,000 MB file limit',
        'WhatsApp, Instagram, Facebook, Telegram',
      ],
    ],
  ],

  'comparison' => [
    ['Contacts', '50,000', '100,000', 'Unlimited'],
    ['Conversations', '50,000', '100,000', 'Unlimited'],
    ['Campaigns / month', '500', '2,000', '10,000'],
    ['AI Prompts', '100', '500', '2,000'],
    ['Team Seats', '3', '10', '25'],
    ['Bot Flows', '25', '50', '150'],
    ['Custom Fields', '—', '60', '100'],
    ['Tags', '30', '60', '100'],
    ['WhatsApp Forms', '—', '60', '100'],
    ['AI Calling Agent credits', '—', '20', '50'],
    ['Appointment Bookings', '—', '20', '50'],
    ['Kanban Funnels', '—', '15', '30'],
    ['Workspaces', '—', '10', '25'],
    ['File Limit', '—', '500 MB', '1,000 MB'],
    ['REST API', '✓', '✓', '✓'],
    ['Webhook', '✓', '✓', '✓'],
    ['Auto Replies', '✓', '✓', '✓'],
    ['Analytics', '✓', '✓', '✓'],
    ['Priority Support', '✓', '✓', '✓'],
    ['Dedicated Account Manager', '✕', '✕', '✓'],
    ['WhatsApp Channel', '✓', '✓', '✓'],
    ['Facebook Messenger', '✕', '✓', '✓'],
    ['Instagram Direct', '✕', '✓', '✓'],
    ['Telegram Bot', '✕', '✓', '✓'],
    ['Mobile App', '✓', '✓', '✓'],
  ],

  'channel_addons' => [
    ['id' => 'instagram', 'name' => 'Add Instagram', 'price' => 799, 'note' => 'Growth plan only'],
    ['id' => 'facebook', 'name' => 'Add Facebook', 'price' => 799, 'note' => 'Growth plan only'],
    ['id' => 'ig_fb_bundle', 'name' => 'Add Both – Bundle', 'price' => 1299, 'note' => 'Growth plan only · Instagram + Facebook'],
  ],

  'capacity_addons' => [
    ['id' => 'contacts_10k', 'name' => '+10,000 contacts', 'price' => 499],
    ['id' => 'campaigns_1k', 'name' => '+1,000 campaigns / month', 'price' => 399],
    ['id' => 'ai_500', 'name' => '+500 AI prompts', 'price' => 599],
    ['id' => 'seats_5', 'name' => '+5 team seats', 'price' => 999],
    ['id' => 'ai_call_5', 'name' => '+5 AI calling agent credits', 'price' => 699],
  ],

  'managed' => [
    'campaign_agent' => [
      'name' => 'Managed Campaign Agent',
      'price' => 3500,
      'description' => 'A dedicated HelloBotz agent can help set up and run campaigns. Share requirements at least 6 hours before launch.',
    ],
    'data_marketplace' => [
      'name' => 'Data Marketplace – Industry Contact Databases',
      'price' => null,
      'description' => 'Verified business contact datasets by industry and volume. Pricing on request. Available separately from subscription.',
    ],
  ],
];
